# Generated by Django 4.2.26 on 2025-11-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_finder_alert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedropalert',
            name='target_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
