# Generated by Django 4.2.26 on 2025-11-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_finder_alert', '0002_alter_pricedropalert_target_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationalerthistory',
            name='alert_type',
            field=models.CharField(choices=[('price', 'Price Alert'), ('open', 'Open'), ('close', 'Close')], max_length=20),
        ),
    ]
