# Generated by Django 4.2.26 on 2025-11-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_finder_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='icon',
            field=models.CharField(blank=True, default='default.png', max_length=200, null=True),
        ),
    ]
