# Generated by Django 4.2.26 on 2025-11-26 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_finder_app', '0002_amenities_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='FuelPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_liter', models.DecimalField(decimal_places=2, max_digits=6)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fuel_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel_finder_app.fuelstations')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel_finder_app.fueltypes')),
            ],
        ),
    ]
