# Generated by Django 4.2.26 on 2025-11-26 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_finder_app', '0003_alter_amenities_icon_fuelprices'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStationTimings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('fuel_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timings', to='fuel_finder_app.fuelstations')),
            ],
        ),
    ]
