# Generated by Django 4.2.26 on 2025-11-27 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_finder_app', '0004_fuelstationtimings'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fuelstationtimings',
            unique_together={('fuel_station', 'day_of_week')},
        ),
    ]
