# Generated by Django 4.2.26 on 2025-11-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_finder_app', '0005_alter_fuelstationtimings_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
