# Generated by Django 4.2.26 on 2025-11-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_finder_app', '0006_cities_latitude_cities_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstationtimings',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
