# Generated by Django 4.2.26 on 2025-11-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_finder_app', '0007_fuelstationtimings_is_open_alter_cities_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstationtimings',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
