# Generated by Django 4.2.26 on 2025-11-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_finder_app', '0008_fuelstationtimings_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='latitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='longitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fuelprices',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='fuelprices',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='fuelstations',
            name='latitude',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='fuelstations',
            name='longitude',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='fuelstationtimings',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], db_index=True),
        ),
        migrations.AddIndex(
            model_name='fuelprices',
            index=models.Index(fields=['fuel_station', 'fuel_type', 'is_active'], name='fuel_finder_fuel_st_9612eb_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelprices',
            index=models.Index(fields=['last_updated'], name='fuel_finder_last_up_b667ed_idx'),
        ),
    ]
